# Generated by Django 4.2.1 on 2023-05-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_excluding_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicable_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price_excluding_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price_including_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_reference', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_excluding_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_including_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_articles',
            },
        ),
    ]
